---

curations:
  packages:
    - id: "NuGet::CommandLineParser:2.9.1"
      curations:
        comment: "A copyright statement was used to declare the license."
        concluded_license: "MIT"
        declared_license_mapping:
          https://www.nuget.org/packages/CommandLineParser/2.9.1/license: "MIT"
